In [1]:
from nb_model import NbModel

/home/dispsiau-2013/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [11]:
generator = NbModel('anum', ['pras1', 'pras2', 'y'], 2)
model = generator.create_model()

In [12]:
model.

      pras1  pras2  y
0         4      4  3
1         2      1  0
2         2      1  0
3         3      3  0
4         3      3  0
5         3      3  0
6         3      3  0
7         3      3  0
8         3      3  0
9         2      3  0
10        2      3  0
11        2      3  0
12        3      2  1
13        3      2  1
14        3      2  1
15        3      2  1
16        3      2  0
17        3      2  0
18        1      1  0
19        1      1  0
20        1      1  0
21        1      2  1
22        1      2  1
23        1      2  1
24        3      3  0
25        3      3  0
26        2      3  0
27        2      3  0
28        2      1  0
29        2      1  0
...     ...    ... ..
1216      1      2  2
1217      3      2  2
1218      3      2  2
1219      2      3  2
1220      2      3  2
1221      3      2  2
1222      2      3  2
1223      2      3  2
1224      3      2  2
1225      3      2  2
1226      3      2  2
1227      3      2  2
1228      1      2  2
1229      1      2  2
1230      3      2  2
1231      1      2  2
1232      3      2  2
1233      2      3  2
1234      3      2  2
1235      2      3  2
1236      3      2  2
1237      3      2  2
1238      2      3  2
1239      1      2  2
1240      1      3  2
1241      3      2  2
1242      3      2  2
1243      1      2  2
1244      2      3  2
1245      2      3  2

[1246 rows x 3 columns]