In [14]:
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE

In [15]:
anum_df = pd.read_csv('anum.csv')

In [3]:
anum_df['hasil'] = anum_df['hasil'].replace("hati hati", 1)
anum_df['hasil'] = anum_df['hasil'].replace("lulus", 2)
anum_df['hasil'] = anum_df['hasil'].replace("tidak lulus", 0)

KeyError: 'hasil'

In [4]:
anum_df

      Unnamed: 0  pras1  pras2            y
0              0    3.0    2.0    hati hati
1              1    3.0    2.0    hati hati
2              2    4.0    4.0    hati hati
3              3    4.0    4.0    hati hati
4              4    4.0    4.0    hati hati
5              5    4.0    4.0    hati hati
6              6    4.0    4.0    hati hati
7              7    4.0    4.0    hati hati
8              8    3.0    4.0    hati hati
9              9    3.0    4.0    hati hati
10            10    3.0    4.0    hati hati
11            11    4.0    3.0        lulus
12            12    4.0    3.0        lulus
13            13    4.0    3.0        lulus
14            14    4.0    3.0        lulus
15            15    4.0    3.0    hati hati
16            16    4.0    3.0    hati hati
17            17    2.0    2.0    hati hati
18            18    2.0    2.0    hati hati
19            19    2.0    2.0    hati hati
20            20    2.0    3.0        lulus
21            21    2.0    3.0        lulus
22            22    2.0    3.0        lulus
23            23    4.0    4.0    hati hati
24            24    4.0    4.0    hati hati
25            25    3.0    4.0    hati hati
26            26    3.0    4.0    hati hati
27            27    3.0    2.0    hati hati
28            28    3.0    2.0    hati hati
29            29    4.0    3.0    hati hati
...          ...    ...    ...          ...
1215        1215    2.0    3.0  tidak lulus
1216        1216    4.0    3.0  tidak lulus
1217        1217    4.0    3.0  tidak lulus
1218        1218    3.0    4.0  tidak lulus
1219        1219    3.0    4.0  tidak lulus
1220        1220    4.0    3.0  tidak lulus
1221        1221    3.0    4.0  tidak lulus
1222        1222    3.0    4.0  tidak lulus
1223        1223    4.0    3.0  tidak lulus
1224        1224    4.0    3.0  tidak lulus
1225        1225    4.0    3.0  tidak lulus
1226        1226    4.0    3.0  tidak lulus
1227        1227    2.0    3.0  tidak lulus
1228        1228    2.0    3.0  tidak lulus
1229        1229    4.0    3.0  tidak lulus
1230        1230    2.0    3.0  tidak lulus
1231        1231    4.0    3.0  tidak lulus
1232        1232    3.0    4.0  tidak lulus
1233        1233    4.0    3.0  tidak lulus
1234        1234    3.0    4.0  tidak lulus
1235        1235    4.0    3.0  tidak lulus
1236        1236    4.0    3.0  tidak lulus
1237        1237    3.0    4.0  tidak lulus
1238        1238    2.0    3.0  tidak lulus
1239        1239    2.0    4.0  tidak lulus
1240        1240    4.0    3.0  tidak lulus
1241        1241    4.0    3.0  tidak lulus
1242        1242    2.0    3.0  tidak lulus
1243        1243    3.0    4.0  tidak lulus
1244        1244    3.0    4.0  tidak lulus

[1245 rows x 4 columns]

In [29]:
anum_df.groupby('hasil').count()

       pras1  pras2
hasil
0         12     12
1        415    415
2        243    243

In [30]:
X = anum_df[['pras1', 'pras2']]
y = anum_df['hasil']
sm = SMOTE()
X_res, y_res = sm.fit_sample(X, y)
X_res = np.round(X_res)
y_res = np.round(y_res)
synthetic_df = pd.DataFrame(X_res)
synthetic_df.columns = X.columns
synthetic_df['y'] = y_res

In [31]:
synthetic_df.groupby('y').count()

   pras1  pras2
y
0    415    415
1    415    415
2    415    415

In [32]:
synthetic_df['y'] = synthetic_df['y'].replace(1, "hati hati")
synthetic_df['y'] = synthetic_df['y'].replace(2, "lulus")
synthetic_df['y'] = synthetic_df['y'].replace(0, "tidak lulus")

In [33]:
synthetic_df.groupby('y').count()

             pras1  pras2
y
hati hati      415    415
lulus          415    415
tidak lulus    415    415

In [13]:
synthetic_df.to_csv('anum.csv', index=False)